---
title: "Organize tex files"
output: html_notebook
---

```{r setup, include=FALSE}
# do not run because files have been renamed
knitr::opts_chunk$set(eval = FALSE)
```

Original data source

```{r}
tex_files_ <- list.files("./src", pattern = "*\\.tex$", full.names = TRUE)
tex_files_
```

```{r}
# get only .tex files; ignore .code.tex
tex_files <- grep(pattern = "\\.code", tex_files_, perl = TRUE, value = TRUE, 
                  invert = TRUE)
tex_files
```

```{r}
# return all files that contain "block"
grep(pattern = ".*block.*", tex_files, perl = TRUE, value = TRUE)
```

```{r}
# files that only have "+block"
tex_block <- grep(pattern = ".*\\+block.*", tex_files, perl = TRUE, value = TRUE)
tex_block
```

```{r}
# remove "+diagram" to avoid repetition later
tex_block_ <- gsub(pattern = "\\+diagram", replacement = "",
     tex_block, perl = TRUE)
tex_block_
```


```{r}
# replace "+block" by "+diagram"
tex_diagram <- gsub(pattern = "\\+block", replacement = "\\+diagram",
     tex_block_, perl = TRUE)
tex_diagram
```

```{r}
# renaming from files tagged with "+block" to new tag "+diagram"
file.rename(from = tex_block, to = tex_diagram)
```

